### ISSUE TITLE
Strange call to unavailable class

### ISSUE THREAD

**Issue by Ace2213** [shukob/humhub-editable-user-tag#1]
`Error: Class 'muhiddin\autocomplete\AutoComplete' not found in /humhub/protected/modules/custom_user_tag/views/tag/create.php:23`

Does this class exist in your environment? How have you added it?

**Comment by shukob** [comment]
Yes! This plugin is dependent on `muhiddingithub/yii2-autocomplete`.
Please see [composer.json](https://github.com/shukob/humhub-editable-user-tag/blob/master/composer.json).
Thank you.
